[package]
name = "script-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "7.1"
regex = "1.10"
printpdf = "0.6"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
